title: Grace Wang
logo: /assets/img/Logo1.jpg
description: Hello there! 
<a href="www.linkedin.com/in/-gracew">👔 LinkedIn</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
